version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: monitoring-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - monitoring-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  api:
    build: .
    container_name: monitoring-api
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=monitoring_poc
      - LOG_LEVEL=info
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - monitoring-network
    volumes:
      - ./app:/app/app
      - ./frontend:/app/frontend
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  monitoring-network:
