version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: monitoring-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "127.0.0.1:27017:27017"  # Bind to localhost only - no external access
    networks:
      - monitoring-network
    healthcheck:
      test: mongosh --username ${MONGODB_USER} --password ${MONGODB_PASSWORD} --eval 'db.runCommand("ping").ok' --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  api:
    build: .
    container_name: monitoring-api
    ports:
      - "127.0.0.1:8000:8000"  # Bind to localhost only - no external access
    environment:
      - MONGODB_URL=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/${DATABASE_NAME}?authSource=admin
      - DATABASE_NAME=${DATABASE_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - monitoring-network
    volumes:
      - ./app:/app/app
      - ./frontend:/app/frontend
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  monitoring-network:
