"""Configuration modules for keywords, patterns, and scoring rules"""
from app.constants.keywords import (
    GOVERNMENT_ENTITIES,
    POLITICAL_KEYWORDS,
    SOCIAL_RELEVANCE_KEYWORDS,
    HEALTH_KEYWORDS,
    SCIENCE_KEYWORDS,
    ATTRIBUTION_KEYWORDS,
    ENTERTAINMENT_KEYWORDS,
    SPORTS_KEYWORDS,
    CONTROVERSY_KEYWORDS,
    SPECULATION_KEYWORDS,
    VAGUE_QUANTIFIERS,
    OFFICIAL_GUIDANCE_KEYWORDS,
    HEALTH_SAFETY_ADVISORY,
    VAGUE_KEYWORDS,
    NOISE_TERMS
)
from app.constants.patterns import (
    PERCENTAGE_PATTERN,
    CURRENCY_BRL_PATTERN,
    CURRENCY_USD_PATTERN,
    LARGE_NUMBER_PATTERN,
    DATE_PATTERN,
    YEAR_PATTERN,
    NUMBER_PATTERN,
    SENTENCE_DELIMITER_PATTERN,
    CONDITIONAL_PATTERN,
    NOISE_PATTERNS,
    PATTERN_ENTITY_VERB_QUE,
    PATTERN_SEGUNDO,
    PATTERN_DE_ACORDO_COM,
    PATTERN_CONFORME,
    PATTERN_ENTITY_VERB_COLON,
    PATTERN_ENTITY_ACTION,
    PATTERN_DIRECT_QUOTE,
    PATTERN_DATA_AFFIRMATION
)
from app.constants.sources import (
    HIGH_CREDIBILITY_SOURCES,
    MEDIUM_CREDIBILITY_SOURCES
)

__all__ = [
    # Keywords
    "GOVERNMENT_ENTITIES",
    "POLITICAL_KEYWORDS",
    "SOCIAL_RELEVANCE_KEYWORDS",
    "HEALTH_KEYWORDS",
    "SCIENCE_KEYWORDS",
    "ATTRIBUTION_KEYWORDS",
    "ENTERTAINMENT_KEYWORDS",
    "SPORTS_KEYWORDS",
    "CONTROVERSY_KEYWORDS",
    "SPECULATION_KEYWORDS",
    "VAGUE_QUANTIFIERS",
    "OFFICIAL_GUIDANCE_KEYWORDS",
    "HEALTH_SAFETY_ADVISORY",
    "VAGUE_KEYWORDS",
    "NOISE_TERMS",
    # Patterns
    "PERCENTAGE_PATTERN",
    "CURRENCY_BRL_PATTERN",
    "CURRENCY_USD_PATTERN",
    "LARGE_NUMBER_PATTERN",
    "DATE_PATTERN",
    "YEAR_PATTERN",
    "NUMBER_PATTERN",
    "SENTENCE_DELIMITER_PATTERN",
    "CONDITIONAL_PATTERN",
    "NOISE_PATTERNS",
    "PATTERN_ENTITY_VERB_QUE",
    "PATTERN_SEGUNDO",
    "PATTERN_DE_ACORDO_COM",
    "PATTERN_CONFORME",
    "PATTERN_ENTITY_VERB_COLON",
    "PATTERN_ENTITY_ACTION",
    "PATTERN_DIRECT_QUOTE",
    "PATTERN_DATA_AFFIRMATION",
    # Sources
    "HIGH_CREDIBILITY_SOURCES",
    "MEDIUM_CREDIBILITY_SOURCES",
]
